Repository sossost/hg_front, pull requests merged in 2023-05, with the labels that each got.

#5 Feature/new post page
  package.json
  src/components/UI/BackBtn.tsx
  src/utils/md-html-parse.ts
Labels: enhancement, 장윤수

#6 Feat : TextInput 컴포넌트 제작
  src/components/UI/TextInput.tsx
Labels: enhancement, 장윤수

#7 Refactor : BackBtn 컴포넌트 리팩토링
  src/components/UI/BackBtn.tsx
Labels: enhancement, 장윤수

#21 Feat : 소셜페이지 구현
  src/components/social/SocialProfile.tsx
  src/components/social/SocialProfileList.tsx
  src/pages/social/FollowerPage.tsx
  src/pages/social/FollowingPage.tsx
Labels: enhancement, 장윤수

#25 Feature/new post page
  package-lock.json
  src/components/UI/TextInput.tsx
  src/components/editor/Editor.tsx
  src/components/editor/EditorModal.tsx
  src/components/editor/TripLocation.tsx
  src/pages/post/NewPostPage.tsx
  src/styles/Editor.css
  src/utils/get-coordinate.ts
  tailwind.config.js
Labels: enhancement

#27 Feat : App.tsx 라우트 추가
  src/App.tsx
Labels: enhancement, 장윤수

#28 Feature/new post page
  package.json
  src/components/editor/Editor.tsx
  tailwind.config.js
Labels: enhancement, 장윤수

#30 Feat: 회원용 Home 화면, Post 컴포넌트, 탐색페이지
  public/icon_heart_empty.svg
  public/icon_heart_full.svg
  public/icon_search.svg
  public/profile_mirabel.webp
  public/thumbnail.jpg
  src/App.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/HeaderModal.tsx
  src/components/UI/Post.tsx
  src/pages/explore/ExplorePage.tsx
  src/pages/home/HomePage.tsx
Labels: enhancement, 황반석

#43 Style : Editor 컴포넌트 css 변경
  src/styles/Editor.css
Labels: enhancement, 장윤수

#44 Feat : 프로필 수정페이지 이미지 업로드 구현
  src/api/api-user.ts
  src/pages/profile/EditProfilePage.tsx
Labels: enhancement, 장윤수

#46 Feat : api 함수들 업데이트
  src/api/api-post.ts
  src/api/api-social.ts
  src/api/api-user.ts
Labels: enhancement, 장윤수

#55 Style : 여행일기 작성페이지 디자인 변경
  src/assets/plusIcon.png
  src/components/editor/Editor.tsx
  src/components/editor/EditorModal.tsx
  src/pages/profile/EditProfilePage.tsx
  src/styles/Editor.css
Labels: 장윤수

#56 Design: 푸터, 메인화면 디자인 수정
  public/bg_planewindow.png
  src/components/Layout/Footer.tsx
  src/pages/home/HomePage.tsx
  src/pages/post/ViewPostPage.tsx
Labels: enhancement, 황반석
